// BuildNumber.cpp : Defines the entry point for the console application.
//
#include "stdio.h"
#include "string.h"
#include "ctype.h"
#include "stdlib.h"

//#define MAXPATH 1024
//#define MAXLINE 1024

int main(int argc, char* argv[])
{
    char filename[1024];
    strcpy(filename,"buildnumber.h");
    char linebuf[1024];
    int nBuild=1;
    if (argc>1)
    {
        char *cmd=argv[1];
        strncpy(filename,cmd,1023);
    }
    printf("BuildNumber 1.0\n");
    printf("© S. Gregory 2016\n");
    FILE *fp=fopen(filename,"r+");
    if (fp)
    {
        memset(linebuf,0,sizeof(linebuf));
        int ctr=0;
        while(fgets(linebuf,1023,fp))
        {
            char *cctr;
            for(cctr=linebuf;*cctr;cctr++)
                *cctr=tolower(*cctr);
            char *pctr=linebuf;
            while((*pctr)&&(isspace(*pctr))) pctr++;
            if (strncmp(pctr,"#define buildnumber",19)==0)
            {
                nBuild=atol(pctr+19)+1;
                fclose(fp);
                fp=fopen(filename,"w");
                if (fp)
                {
                    fprintf(fp,"/* Generated by BuildNumber Version 1.0 */\r\n\r\n");
                    fprintf(fp,"#ifndef BUILD_NUMBER_H_\r\n");
                    fprintf(fp,"#define BUILD_NUMBER_H_\r\n\r\n");
                    fprintf(fp,"#define BUILDNUMBER %d\r\n",nBuild);
                    fprintf(fp,"#define BUILDNUMBER_STR \"%04d\"\r\n",nBuild);
                    fprintf(fp,"#endif /* BUILD_NUMBER_H_ */\r\n");
                    printf("Build %d\n",nBuild);
                    fclose(fp);
                    return 0;
                }
                else
                {
                    printf("File Open Error\r\n");
                }
                return -1;
            }
        }
        printf("%s not valid\r\n",filename);
        fclose(fp);
        return -2;
    }
    else
    {
        fp=fopen(filename,"w");
        if (fp)
        {
            fprintf(fp,"/* Generated by BuildNumber Version 1.0 */\r\n\r\n");
            fprintf(fp,"#ifndef BUILD_NUMBER_H_\r\n");
            fprintf(fp,"#define BUILD_NUMBER_H_\r\n\r\n");
            fprintf(fp,"#define BUILDNUMBER %d\r\n",nBuild);
            fprintf(fp,"#define BUILDNUMBER_STR \"%04d\"\r\n",nBuild);
            fprintf(fp,"#endif /* BUILD_NUMBER_H_ */\r\n");
        }
        else
        {
            printf("File Open Error\r\n");
            return -1;
        }
        fclose(fp);
        printf("Build %d\n",nBuild);
        return 0;
    }
    return -3;
}